
#+TITLE: ConCR-TMLE R Paper
#+Author: David Chen, Thomas Gerds, Helene Rytgaard
#+Date: 
#+EMAIL: 
#+LANGUAGE:  en
#+OPTIONS: H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+LaTeX_CLASS: Rnews-article
#+LaTeX_HEADER:\usepackage[utf8]{inputenc}
#+LaTeX_HEADER:\usepackage[T1]{fontenc}
#+LaTeX_HEADER:\usepackage{amsmath,amssymb,array}
#+LaTeX_HEADER:\usepackage{booktabs}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage{listings}
#+LaTeX_HEADER:\newcommand{\J}{\ensuremath{J}}
#+LaTeX_HEADER:\newcommand{\1}{\ensuremath{\mathbf{1}}}
#+LaTeX_HEADER:\DeclareMathOperator*{\argmax}{argmax}
#+LaTeX_HEADER:\DeclareMathOperator*{\argmin}{argmin}
#+LaTeX_HEADER:\newcommand{\h}{\ensuremath{\lambda}}
#+LaTeX_HEADER:\newcommand{\T}{\ensuremath{\widetilde{T}}}
#+LaTeX_HEADER:\newcommand{\X}{\ensuremath{\mathbf{X}}}
#+LaTeX_HEADER:\renewcommand{\t}{\ensuremath{\Tilde{t}}}
#+LaTeX_HEADER:\newcommand{\ax}{\ensuremath{\mid a,\,\mathbf{x}}}
#+LaTeX_HEADER:\newcommand{\aX}{\ensuremath{\mid A = a,\,\mathbf{X}}}
#+LaTeX_HEADER:\newcommand{\AX}{\ensuremath{\mid A,\,\mathbf{X}}}
#+LaTeX_HEADER:\newcommand{\x}{\ensuremath{\mathbf{x}}}
#+LaTeX_HEADER:\newcommand{\trt}{\ensuremath{a^*}}
#+LaTeX_HEADER:\newcommand{\tk}{\ensuremath{\tau}}
#+LaTeX_HEADER:\newcommand{\jj}{\ensuremath{k}}
#+LaTeX_HEADER:\newcommand{\g}{\ensuremath{\pi}}
#+setupfile:~/emacs-genome/snps/org-templates/setup-all-purpose.org
#+superman-export-target: pdf

#+begin_export latex
\abstract{
An abstract of less than 150 words.
}
#+end_export

* Introduction

* Data Structure

Consider a survival analysis on an interval $[0,\,t_{max}]$ with competing risks. Let $T^a_j$ denote counterfactual time-to-event variables for event $j$ and intervention $a$, for competing events $j \in \mathcal{J} = \{1, 2, \dots, J\}$ and an intervention $a \in \mathcal{A}$. Our counterfactual data structure can then be denoted by
\[(T^a_j,\;\X\,:\;a\in\mathcal{A},\;j\in\mathcal{J})\]
where $\X \in \mathbb{R}^d$ is a $d$-dimensional vector of baseline covariates. For a single time-point binary intervention, as in many randomized control trials, $\mathcal{A} = \{0, 1\}$ and the corresponding counterfactual data is 
\[ (T^1_j,\; T^0_j,\;\X\,: \;j\in\mathcal{J})\]

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
  ## sample data.table for counterfactual data
#+END_SRC

#+begin_export latex
\noindent Let $O$ denote the corresponding coarsened observed data where $O \sim P_0$. The observed data would include the time-to-censoring $C$, and observed intervention $A$. The time to first event (censoring or otherwise) we denote as $\T = \min(C,\; T_j\,: \; j \in \mathcal{J})$ with $\Delta = (\argmin\limits_j T_j) \times \1(\min\limits_j T_j \leq C)$ marking which outcome is observed ($\Delta = 0$ being that censoring occurred). The observable right-censored survival data with competing events can then be represented as 
\[O = (\T,\;\Delta,\;A,\;\X)\]
#+end_export

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
  ## sample data.table of the observed data correlating to the above counterfactual data example
#+END_SRC

This observed data also allows the ``long-format'' formulation, where
with single time-point intervention variable $A$ and baseline
covariate vector $\X$, \[O = (N_j(t),\;N_c(t),\;A,\;\X\,:\,
j\in\mathcal{J}, t \leq \T)\] Here $N_j(t) = \1(\T \leq t, \Delta =
j)$ and $N_c(t) = \1(\T \leq t, \Delta = 0)$ denote counting processes
for event $j$ and censoring respectively.

Under coarsening at random (CAR), the observed data likelihood can be factorized as 
\[p(O) = p(\X)\, \g(A \mid \X)\, \lambda_c(\T \AX)^{\1(\Delta = 0)} S_c(\T\text{-} \AX) \prod_{j=1}^{J} S(\T\text{-} \AX) \lambda_j(\T \AX)^{\1(\Delta = j)} \]
where $\lambda_c(t \AX)$ is the hazard of the censoring process and $\lambda_j(t \AX)$ is the hazard of the $j^{th}$ event process. Additionally 
\[S_c(t \ax) = \exp\left(-\int_{0}^{t} \lambda_c(s \ax) \,ds\right)\]  
while in a pure competing risks setting 

#+begin_export latex
\begin{align*}
    S(t \ax) &= \exp\left(-\int_{0}^{t} \sum_{j=1}^{J} \lambda_j(s \ax) \,ds\right)
\intertext{and} 
    F_j(t \ax) &= \int_{0}^{t} S(s\text{-} \ax) \lambda_j(s \ax)\,ds\\
    &= \int_{0}^{t} \exp\bigg(-\int_{0}^{s} \sum_{j=1}^{J} \lambda_j(u \ax)\,du\bigg) \lambda_j(s \ax)\,ds.
\end{align*}
#+end_export

* Target Parameter

#+begin_export latex
% Given identifiability assumptions, for a desired treatment regime $A = \trt \in \{0, 1\}$ and prevention of the censoring process, the post-intervention distribution is 
% \[p(o) = p(\x)\, \1(a = \trt)\, \prod_{j=1}^{J} S(\t\text{-} \ax) \lambda_j(\t \ax)^{\1(\delta = j)}\]
For a target parameter of the treatment regime $\trt$, cause $\jj \in \J$ cumulative risk at time $\tk$
\begin{align*}
    \Psi_{\trt, \jj, \tk}(P_0) &= \mathbb{E}\left[F_\jj(\tk \mid A = \trt,\,\X)\right]
\end{align*}
the corresponding efficient influence function $D^{*}_{\trt, \jj, \tk}(P)(O) $ is
\begin{align*}
    \sum_{j = 1}^{J} \int_{0}^{\tk} &\frac{\1(A = \trt)\, \1(s \leq \tk)}{\g(A \mid \X)\,S_c(s\text{-} \AX)} \left(\1(\delta = \jj) - \frac{F_\jj(\tk \AX) - F_\jj(s \AX)}{S(s \AX)}\right) \\ &\left(N_j(ds) - \1(\T \geq s)\,\lambda_j(s \AX)\right) \,ds\\[2mm]
    &\hspace{2cm}+ F_\jj(t \mid A = \trt,\,\X) - \Psi_{\trt, \jj, \tk}(P_0)
\end{align*}

with a clever covariate  $h_{\trt, \jj, j, \tk, s}$ 
\begin{align*}
    h_{\trt,\, \jj,\, j,\, \tk,\, s} = \frac{\1(A = \trt)\, \1(s \leq \tk)}{\g(A \mid \X) S_c(s\text{-} \AX)} \left(\1(\delta = \jj) - \frac{F_\jj(\tk \AX) - F_\jj(s \AX)}{S(s \AX)}\right)
\end{align*}

The components of the data distribution that must be estimated are $g(A \mid \X)$ and $S_c(t \AX)$, $\lambda_j(t \AX)$, $F_j(t \AX)$, and $S(t \AX)$
#+end_export

* Estimation
** Cross-Validation Specification
Let $D_n = \{O_i\}_{i=1}^n$ be an observed sample of $n$ i.i.d observations of $O \sim P_0$. For $V\text{-fold}$ cross validation, let $B_n = \{1, ... , V\}^n$ be a random vector that assigns the $n$ observations into $V$ validation folds. For each $v \in \{1, ..., V\}$ we then define training set $D^\mathcal{T}_v = \{O_i : B_n(i) = v\}$ with the corresponding validation set $D^\mathcal{V}_v = \{O_i : B_n(i) \neq v\}$.

*** Stratified Cross-Validation

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
  # StrataIDs <- as.numeric(factor(paste0(Data[["Trt"]], ":", Data[["Event"]])))
  # CVFolds <- origami::make_folds(n = Data, fold_fun = origami::folds_vfold, strata_ids = StrataIDs)
#+END_SRC

** Propensity Score Estimation

#+begin_export latex
For the conditional distribution of $A$ given $\X$, $\pi(\cdot \mid \X)$, and $\Hat{\pi} : D_n \to \Hat{\pi}(D_n)$, let $L_\pi$ be a loss function such that the risk $\mathbb{E}_0\left[L_\pi(\Hat{\pi}, O)\right]$ is minimized when $\Hat{\pi} = \pi_0$. For instance, with a binary $A$, we may specify the negative log loss $L_\pi(\Hat{\pi}, O) = \text{-}\log\left(\Hat{\pi}(1 \mid \X)^A \; \Hat{\pi}(0 \mid \X))^{1-A}\right)$. Let $\mathcal{M_\pi}$ be the set of candidate propensity score models. The discrete superlearner selector chooses the candidate propensity score model with the minimal cross validated risk 
\[ \Hat{\pi}^{SL} = \argmin_{\Hat{\pi} \in \mathcal{M}_\pi} \sum_{v = 1}^{V} P_{D^\mathcal{V}_v} \; L_\pi(\Hat{\pi}(D^\mathcal{T}_v), D^\mathcal{V}_v)\]
#+end_export

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
 getInitialEstimates <- function(...) {
   getPropScores <- function(...) {
     getSl3PropScores <- function {
       TrtTask <- sl3::make_sl3_Task(
        data = Data[, -c("Time", "Event", "ID")],
        covariates = colnames(CovDataTable),
        outcome = "Trt")

    TrtSL <- sl3::Lrnr_sl$new(learners = Models[["A"]], folds = CVFolds)
    TrtFit <- TrtSL$train(TrtTask)
     }
   }
 }
#+END_SRC
